import { PrismaClient } from '../src/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is required');
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const preguntas = [
  // Bloque 1: Toma de Decisiones y Retos
  {
    numero: 1,
    bloque: 'Bloque 1: Toma de Decisiones y Retos',
    texto: 'Tienes que lanzar un proyecto urgente, pero la información está incompleta. ¿Qué haces?',
    opcionA: 'Confío en mi intuición y lanzo el proyecto; ajustaremos sobre la marcha.',
    opcionB: 'Busco a alguien con experiencia para que me dé su opinión antes de decidir.',
    opcionC: 'Reviso los datos disponibles y hago un análisis de riesgos antes de moverme.',
    opcionD: 'Convoco una reunión rápida para motivar al equipo y obtener ideas de todos.',
    claveA: 'D',
    claveB: 'S',
    claveC: 'C',
    claveD: 'I',
  },
  {
    numero: 2,
    bloque: 'Bloque 1: Toma de Decisiones y Retos',
    texto: 'Un cliente importante está molesto y exige una solución inmediata que va contra las reglas.',
    opcionA: 'Le explico las políticas amablemente pero con firmeza; las reglas son para todos.',
    opcionB: 'Le ofrezco una solución creativa y le invito a comer para calmar las aguas.',
    opcionC: 'Tomo la decisión de hacer la excepción si eso salva el negocio; yo asumo la culpa.',
    opcionD: 'Escucho pacientemente, le pido disculpas y busco una solución que no altere el orden.',
    claveA: 'C',
    claveB: 'I',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 3,
    bloque: 'Bloque 1: Toma de Decisiones y Retos',
    texto: 'Tu jefe te asigna una meta extremadamente ambiciosa para este mes.',
    opcionA: 'Me emociona el reto; me pongo a trabajar de inmediato para superarla.',
    opcionB: 'Me preocupa si es realista y si tendremos los recursos necesarios.',
    opcionC: 'Organizo un plan detallado paso a paso para asegurar que no fallemos.',
    opcionD: 'Hablo con el equipo para venderles la idea y que se entusiasmen con el logro.',
    claveA: 'D',
    claveB: 'S',
    claveC: 'C',
    claveD: 'I',
  },
  {
    numero: 4,
    bloque: 'Bloque 1: Toma de Decisiones y Retos',
    texto: 'Hay un cambio repentino en el software de gestión de la empresa.',
    opcionA: 'Me frustra un poco si no veo la lógica, pero estudio el manual para dominarlo.',
    opcionB: 'Me adapto rápido, siempre y cuando no afecte mis relaciones con los demás.',
    opcionC: 'Pregunto "¿Por qué el cambio?" y si es eficiente, lo adopto rápido.',
    opcionD: 'Me cuesta adaptarme; prefería el sistema anterior porque ya lo conocía bien.',
    claveA: 'C',
    claveB: 'I',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 5,
    bloque: 'Bloque 1: Toma de Decisiones y Retos',
    texto: 'Debes despedir a un colaborador que es buena persona pero no da resultados.',
    opcionA: 'Le doy vueltas al asunto y trato de darle otra oportunidad para no herirlo.',
    opcionB: 'Voy al grano, le explico los hechos y procedo con el despido rápido.',
    opcionC: 'Le explico con datos y evaluaciones por qué no cumple el estándar requerido.',
    opcionD: 'Trato de hacerlo sentir bien, destacando sus cualidades para que no se vaya triste.',
    claveA: 'S',
    claveB: 'D',
    claveC: 'C',
    claveD: 'I',
  },

  // Bloque 2: Comunicación y Trabajo en Equipo
  {
    numero: 6,
    bloque: 'Bloque 2: Comunicación y Trabajo en Equipo',
    texto: 'En una reunión de equipo, tu rol natural suele ser:',
    opcionA: 'El que anima, hace chistes y mantiene la energía alta.',
    opcionB: 'El que escucha, toma notas y asegura que todos estén cómodos.',
    opcionC: 'El que dirige la agenda y corta las conversaciones irrelevantes.',
    opcionD: 'El que cuestiona los detalles y busca la precisión en lo que se dice.',
    claveA: 'I',
    claveB: 'S',
    claveC: 'D',
    claveD: 'C',
  },
  {
    numero: 7,
    bloque: 'Bloque 2: Comunicación y Trabajo en Equipo',
    texto: 'Tienes que convencer a un inversor escéptico.',
    opcionA: 'Le muestro gráficos, estadísticas y proyecciones financieras exactas.',
    opcionB: 'Le cuento una historia apasionante sobre el futuro y el impacto del proyecto.',
    opcionC: 'Le demuestro seguridad y le garantizo resultados con firmeza.',
    opcionD: 'Le doy tiempo para pensarlo y respondo sus dudas con paciencia y lealtad.',
    claveA: 'C',
    claveB: 'I',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 8,
    bloque: 'Bloque 2: Comunicación y Trabajo en Equipo',
    texto: 'Un compañero de trabajo te critica públicamente.',
    opcionA: 'Me defiendo al instante; no dejo que nadie me pase por encima.',
    opcionB: 'Me siento mal y probablemente lo comente con otros para desahogarme.',
    opcionC: 'Analizo si su crítica tiene fundamento lógico; si no, la ignoro.',
    opcionD: 'Trato de ignorarlo en el momento para evitar una escena y mantener la paz.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'C',
    claveD: 'S',
  },
  {
    numero: 9,
    bloque: 'Bloque 2: Comunicación y Trabajo en Equipo',
    texto: 'Lo que más valoras de un ambiente de trabajo es:',
    opcionA: 'Que sea divertido, dinámico y con gente interesante.',
    opcionB: 'Que sea predecible, seguro y con buen compañerismo.',
    opcionC: 'Que sea eficiente, orientado a resultados y sin burocracia.',
    opcionD: 'Que sea organizado, estructurado y con reglas claras.',
    claveA: 'I',
    claveB: 'S',
    claveC: 'D',
    claveD: 'C',
  },
  {
    numero: 10,
    bloque: 'Bloque 2: Comunicación y Trabajo en Equipo',
    texto: 'Te piden liderar un comité de festejos o integración.',
    opcionA: 'Acepto encantado, me encanta organizar eventos y conectar gente.',
    opcionB: 'Acepto si es necesario, pero prefiero seguir un plan ya hecho.',
    opcionC: 'Lo delego; prefiero enfocarme en tareas productivas del negocio.',
    opcionD: 'Hago una lista de todo lo necesario para asegurar que no falte nada.',
    claveA: 'I',
    claveB: 'S',
    claveC: 'D',
    claveD: 'C',
  },

  // Bloque 3: Gestión de Tareas y Organización
  {
    numero: 11,
    bloque: 'Bloque 3: Gestión de Tareas y Organización',
    texto: 'Tu escritorio o espacio de trabajo suele estar:',
    opcionA: 'Lleno de cosas, premios o fotos, un poco desordenado pero inspirador.',
    opcionB: 'Muy limpio, minimalista y con todo en su lugar exacto.',
    opcionC: 'Funcional; tengo lo que necesito a la mano para trabajar rápido.',
    opcionD: 'Ordenado y acogedor, tal vez con plantas o recuerdos familiares.',
    claveA: 'I',
    claveB: 'C',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 12,
    bloque: 'Bloque 3: Gestión de Tareas y Organización',
    texto: 'Al planificar tu semana, tú prefieres:',
    opcionA: 'Tener una lista de objetivos clave, el resto lo decido sobre la marcha.',
    opcionB: 'Usar una agenda detallada por horas y categorizada por colores.',
    opcionC: 'Seguir la rutina de siempre, no me gusta variar mucho mis horarios.',
    opcionD: 'Anotar citas y reuniones, pero dejar espacio para lo social e imprevistos.',
    claveA: 'D',
    claveB: 'C',
    claveC: 'S',
    claveD: 'I',
  },
  {
    numero: 13,
    bloque: 'Bloque 3: Gestión de Tareas y Organización',
    texto: 'Descubres un error en un reporte que ya se envió.',
    opcionA: 'Mando una corrección inmediata con los datos precisos y una disculpa formal.',
    opcionB: 'Llamo para explicarlo y minimizar la gravedad con encanto.',
    opcionC: 'Me molesta, pero asumo la responsabilidad y busco cómo arreglarlo ya.',
    opcionD: 'Espero que no se den cuenta o lo corrijo discretamente después.',
    claveA: 'C',
    claveB: 'I',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 14,
    bloque: 'Bloque 3: Gestión de Tareas y Organización',
    texto: 'Para ti, el "éxito" se define como:',
    opcionA: 'Tener poder, control y superar a la competencia.',
    opcionB: 'Ser reconocido, admirado y tener influencia sobre las personas.',
    opcionC: 'Hacer el trabajo perfecto, sin errores y con calidad superior.',
    opcionD: 'Tener estabilidad, paz mental y buenas relaciones a largo plazo.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'C',
    claveD: 'S',
  },
  {
    numero: 15,
    bloque: 'Bloque 3: Gestión de Tareas y Organización',
    texto: 'Cuando tienes demasiadas tareas a la vez:',
    opcionA: 'Priorizo lo urgente y delego el resto sin pensarlo mucho.',
    opcionB: 'Me estreso un poco y trato de terminar una por una con cuidado.',
    opcionC: 'Me agobio y busco a alguien que me ayude a salir del apuro.',
    opcionD: 'Hago una matriz de prioridades y organizo sistemáticamente el flujo.',
    claveA: 'D',
    claveB: 'S',
    claveC: 'I',
    claveD: 'C',
  },

  // Bloque 4: Motivación y Estilo de Venta
  {
    numero: 16,
    bloque: 'Bloque 4: Motivación y Estilo de Venta',
    texto: 'Si tuvieras que vender un producto, tu estrategia sería:',
    opcionA: 'Ganarme la amistad del cliente y hacer que disfrute la compra.',
    opcionB: 'Explicar las características técnicas y la garantía de calidad.',
    opcionC: 'Cerrar el trato rápido ofreciendo un beneficio exclusivo o descuento.',
    opcionD: 'Escuchar sus necesidades y ofrecerle solo lo que realmente le sirva.',
    claveA: 'I',
    claveB: 'C',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 17,
    bloque: 'Bloque 4: Motivación y Estilo de Venta',
    texto: 'Te motiva más recibir:',
    opcionA: 'Un bono económico por resultados alcanzados.',
    opcionB: 'Un reconocimiento público frente a toda la empresa.',
    opcionC: 'Una carta de agradecimiento sincera y privada.',
    opcionD: 'Una evaluación de desempeño perfecta y sin errores.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'S',
    claveD: 'C',
  },
  {
    numero: 18,
    bloque: 'Bloque 4: Motivación y Estilo de Venta',
    texto: 'En un proyecto grupal, te molesta más:',
    opcionA: 'Que la gente pierda el tiempo hablando y no trabaje.',
    opcionB: 'Que sean fríos, distantes o demasiado críticos.',
    opcionC: 'Que no haya instrucciones claras y todo sea un caos.',
    opcionD: 'Que me presionen demasiado y no respeten mi ritmo.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'C',
    claveD: 'S',
  },
  {
    numero: 19,
    bloque: 'Bloque 4: Motivación y Estilo de Venta',
    texto: 'Ante una nueva tecnología disruptiva en tu industria:',
    opcionA: 'Soy el primero en probarla y evangelizar sobre ella.',
    opcionB: 'Espero a ver si funciona para otros antes de arriesgarme.',
    opcionC: 'La analizo para ver si realmente mejora la eficiencia o es moda.',
    opcionD: 'Veo cómo puedo usarla para ganar ventaja competitiva rápido.',
    claveA: 'I',
    claveB: 'S',
    claveC: 'C',
    claveD: 'D',
  },
  {
    numero: 20,
    bloque: 'Bloque 4: Motivación y Estilo de Venta',
    texto: 'Al dar feedback a un subordinado:',
    opcionA: 'Soy directo y duro si es necesario; lo que importa es que mejore.',
    opcionB: 'Uso la técnica del "sándwich" (positivo-negativo-positivo) para no ofender.',
    opcionC: 'Me baso estrictamente en el manual de procedimientos y sus métricas.',
    opcionD: 'Le pregunto cómo se siente y tratamos de buscar soluciones juntos.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'C',
    claveD: 'S',
  },

  // Bloque 5: Reacción bajo Presión
  {
    numero: 21,
    bloque: 'Bloque 5: Reacción bajo Presión',
    texto: 'Faltan 2 horas para una entrega y parece imposible llegar.',
    opcionA: '"¡Vamos equipo, sí se puede!" (Doy porras aunque no haga mucho).',
    opcionB: 'Me arremango y trabajo el doble de rápido, exigiendo a todos lo mismo.',
    opcionC: 'Me paralizo un poco y pregunto: "¿Qué fue lo que salió mal?".',
    opcionD: 'Negocio una extensión de tiempo con el cliente para entregar calidad.',
    claveA: 'I',
    claveB: 'D',
    claveC: 'C',
    claveD: 'S',
  },
  {
    numero: 22,
    bloque: 'Bloque 5: Reacción bajo Presión',
    texto: 'Alguien sugiere una idea muy arriesgada en una junta.',
    opcionA: 'La apoyo de inmediato si suena innovadora y divertida.',
    opcionB: 'La rechazo si no veo datos que la respalden.',
    opcionC: 'Pregunto: "¿Cuál es el retorno de inversión y quién se hace responsable?".',
    opcionD: 'Me mantengo callado esperando ver qué opinan la mayoría.',
    claveA: 'I',
    claveB: 'C',
    claveC: 'D',
    claveD: 'S',
  },
  {
    numero: 23,
    bloque: 'Bloque 5: Reacción bajo Presión',
    texto: 'Tu mayor miedo en el entorno laboral es:',
    opcionA: 'Perder la seguridad o que haya cambios bruscos.',
    opcionB: 'Cometer un error grave y ser criticado por mi incompetencia.',
    opcionC: 'Perder mi estatus, autonomía o que se aprovechen de mí.',
    opcionD: 'Ser ignorado, rechazado o perder popularidad.',
    claveA: 'S',
    claveB: 'C',
    claveC: 'D',
    claveD: 'I',
  },
  {
    numero: 24,
    bloque: 'Bloque 5: Reacción bajo Presión',
    texto: 'Cuando viajas por negocios, prefieres:',
    opcionA: 'Tener la agenda llena de reuniones productivas y cerrar tratos.',
    opcionB: 'Tener tiempo libre para conocer la ciudad y socializar.',
    opcionC: 'Tener todo el itinerario impreso, boletos y reservaciones confirmadas.',
    opcionD: 'Que el viaje sea tranquilo, sin prisas y cómodo.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'C',
    claveD: 'S',
  },
  {
    numero: 25,
    bloque: 'Bloque 5: Reacción bajo Presión',
    texto: 'Si pudieras cambiar algo de tu personalidad en el trabajo:',
    opcionA: 'Sería más paciente y escucharía más a los demás.',
    opcionB: 'Sería más organizado y detallista.',
    opcionC: 'Sería más atrevido y tomaría decisiones más rápido.',
    opcionD: 'Sería menos perfeccionista y me relajaría más.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'S',
    claveD: 'C',
  },

  // Bloque 6: Liderazgo y Visión
  {
    numero: 26,
    bloque: 'Bloque 6: Liderazgo y Visión',
    texto: 'Como líder, tu estilo se define como:',
    opcionA: 'Democrático: busco el consenso y la armonía.',
    opcionB: 'Visionario: inspiro con grandes ideas y carisma.',
    opcionC: 'Autoritario: doy instrucciones claras y espero obediencia.',
    opcionD: 'Analítico: guío con base en procesos y estándares altos.',
    claveA: 'S',
    claveB: 'I',
    claveC: 'D',
    claveD: 'C',
  },
  {
    numero: 27,
    bloque: 'Bloque 6: Liderazgo y Visión',
    texto: 'Para resolver un problema complejo:',
    opcionA: 'Lo rompo en partes pequeñas y lo analizo lógicamente.',
    opcionB: 'Busco una solución práctica y rápida para seguir avanzando.',
    opcionC: 'Hago una lluvia de ideas con otros para ver opciones creativas.',
    opcionD: 'Busco antecedentes de cómo se resolvió antes para ir a lo seguro.',
    claveA: 'C',
    claveB: 'D',
    claveC: 'I',
    claveD: 'S',
  },
  {
    numero: 28,
    bloque: 'Bloque 6: Liderazgo y Visión',
    texto: 'Cuando alguien llega tarde a una reunión contigo:',
    opcionA: 'Me ofende, es una falta de respeto a mi tiempo.',
    opcionB: 'No le doy importancia, a mí también me pasa a veces.',
    opcionC: 'Me preocupa que le haya pasado algo malo.',
    opcionD: 'Le marco el retraso y anoto la incidencia mentalmente.',
    claveA: 'D',
    claveB: 'I',
    claveC: 'S',
    claveD: 'C',
  },
  {
    numero: 29,
    bloque: 'Bloque 6: Liderazgo y Visión',
    texto: 'En una discusión acalorada:',
    opcionA: 'Levanto la voz si es necesario para imponer mi punto.',
    opcionB: 'Cedo para evitar pelear, aunque no esté de acuerdo.',
    opcionC: 'Uso argumentos lógicos y fríos para desarmar al otro.',
    opcionD: 'Trato de mediar y suavizar la tensión con una broma.',
    claveA: 'D',
    claveB: 'S',
    claveC: 'C',
    claveD: 'I',
  },
  {
    numero: 30,
    bloque: 'Bloque 6: Liderazgo y Visión',
    texto: 'Al final del día, te sientes satisfecho si:',
    opcionA: 'Ayudé a alguien y el ambiente fue agradable.',
    opcionB: 'Taché todos los pendientes de mi lista sin errores.',
    opcionC: 'Logré un avance significativo o cerré un negocio.',
    opcionD: 'Conocí gente nueva o tuve conversaciones estimulantes.',
    claveA: 'S',
    claveB: 'C',
    claveC: 'D',
    claveD: 'I',
  },
];

async function main() {
  console.log('Iniciando seed de preguntas...');

  for (const pregunta of preguntas) {
    await prisma.pregunta.upsert({
      where: { numero: pregunta.numero },
      update: {},
      create: pregunta,
    });
    console.log(`✓ Pregunta ${pregunta.numero} insertada`);
  }

  console.log('✅ Seed completado: 30 preguntas insertadas exitosamente');
}

main()
  .catch((e) => {
    console.error('Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
